sources:
  - name: department
    handler:
      graphql:
        endpoint: '{env.DEPARTMENT_API_URL}/graphql'
  - name: employee
    handler:
      graphql:
        endpoint: '{env.EMPLOYEE_API_URL}/graphql'
  - name: salary
    handler:
      graphql:
        endpoint: '{env.SALARY_API_URL}/graphql'
  - name: title
    handler:
      graphql:
        endpoint: '{env.TITLE_API_URL}/graphql'
additionalTypeDefs: |
  extend type Department {
    """
    현재 부서에 속한 직원 목록
    """
    employees(offset: Int, limit: Int): Employees! @resolveTo(
      sourceName: "employee",
      sourceTypeName: "Query",
      sourceFieldName: "listEmployeesByDepartmentId",
      requiredSelectionSet: "{ id }",
      sourceArgs: {
        departmentId: "{root.id}",
      }
    )
  
    """
    부서에 속한 직원 내역 목록
    """
    employeeLogs(offset: Int, limit: Int): EmployeeLogs! @resolveTo(
      sourceName: "employee",
      sourceTypeName: "Query",
      sourceFieldName: "listEmployeeLogsByDepartmentId",
      requiredSelectionSet: "{ id }",
      sourceArgs: {
        departmentId: "{root.id}",
      }
    )
  }
  extend type Employee {
    """
    소속 부서
    """
    department: Department! @resolveTo(
      sourceName: "department",
      sourceTypeName: "Query",
      sourceFieldName: "department",
      requiredSelectionSet: "{ departmentId }",
      sourceArgs: {
        id: "{root.departmentId}"
      }
    )
  
    """
    소속 부서 내역
    """
    departmentLogs(fromDateTime: DateTime!, toDateTime: DateTime!): [DepartmentLog!]! @resolveTo(
      sourceName: "department",
      sourceTypeName: "Query",
      sourceFieldName: "listDepartmentLogByEmployeeId",
      requiredSelectionSet: "{ id }",
      sourceArgs: {
        employeeId: "{root.id}",
      }
    )
    
    """
    연봉 내역
    """
    salaryLogs(fromDateTime: DateTime!, toDateTime: DateTime!): [SalaryLog!]! @resolveTo(
      sourceName: "salary",
      sourceTypeName: "Query",
      sourceFieldName: "listSalaryLogByEmployeeIds",
      keyField: "id",
      keysArg: "employeeIds",
    )
  
    """
    직급 내역
    """
    titleLogs(fromDateTime: DateTime!, toDateTime: DateTime!): [TitleLog!]! @resolveTo(
      sourceName: "title",
      sourceTypeName: "Query",
      sourceFieldName: "listTitleLogByEmployeeIds",
      keyField: "id",
      keysArg: "employeeIds",
    )  
  }
transforms:
  - filterSchema:
      filters:
        - Query.!listEmployeesByDepartmentId
        - Query.!listEmployeeLogsByDepartmentId
        - Query.!listDepartmentLogByEmployeeId
        - Query.!listSalaryLogByEmployeeId
        - Query.!listSalaryLogByEmployeeIds
        - Query.!listTitleLogByEmployeeId
        - Query.!listTitleLogByEmployeeIds
serve:
  port: 3000